/* 
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace Environment API v2. Resources here generally supersede those in v1. Migration of resources from v1 is in progress. If you miss a resource, consider using the Dynatrace Environment API v1. To read about use cases and examples, see [Dynatrace Documentation](https://dt-url.net/2u23k1k) .Notes about compatibility:* Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this.* We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Dynatrace.API.Client.SwaggerDateConverter;

namespace Dynatrace.API.Model
{
    /// <summary>
    /// The result of closing a problem.
    /// </summary>
    [DataContract]
        public partial class ProblemCloseResult :  IEquatable<ProblemCloseResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProblemCloseResult" /> class.
        /// </summary>
        /// <param name="closeTimestamp">The timestamp when the user triggered the closing. (required).</param>
        /// <param name="problemId">The ID of the problem. (required).</param>
        /// <param name="closing">True, if the problem is being closed. (required).</param>
        /// <param name="comment">comment.</param>
        public ProblemCloseResult(long? closeTimestamp = default(long?), string problemId = default(string), bool? closing = default(bool?), Comment comment = default(Comment))
        {
            // to ensure "closeTimestamp" is required (not null)
            if (closeTimestamp == null)
            {
                throw new InvalidDataException("closeTimestamp is a required property for ProblemCloseResult and cannot be null");
            }
            else
            {
                this.CloseTimestamp = closeTimestamp;
            }
            // to ensure "problemId" is required (not null)
            if (problemId == null)
            {
                throw new InvalidDataException("problemId is a required property for ProblemCloseResult and cannot be null");
            }
            else
            {
                this.ProblemId = problemId;
            }
            // to ensure "closing" is required (not null)
            if (closing == null)
            {
                throw new InvalidDataException("closing is a required property for ProblemCloseResult and cannot be null");
            }
            else
            {
                this.Closing = closing;
            }
            this.Comment = comment;
        }
        
        /// <summary>
        /// The timestamp when the user triggered the closing.
        /// </summary>
        /// <value>The timestamp when the user triggered the closing.</value>
        [DataMember(Name="closeTimestamp", EmitDefaultValue=false)]
        public long? CloseTimestamp { get; set; }

        /// <summary>
        /// The ID of the problem.
        /// </summary>
        /// <value>The ID of the problem.</value>
        [DataMember(Name="problemId", EmitDefaultValue=false)]
        public string ProblemId { get; set; }

        /// <summary>
        /// True, if the problem is being closed.
        /// </summary>
        /// <value>True, if the problem is being closed.</value>
        [DataMember(Name="closing", EmitDefaultValue=false)]
        public bool? Closing { get; set; }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [DataMember(Name="comment", EmitDefaultValue=false)]
        public Comment Comment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProblemCloseResult {\n");
            sb.Append("  CloseTimestamp: ").Append(CloseTimestamp).Append("\n");
            sb.Append("  ProblemId: ").Append(ProblemId).Append("\n");
            sb.Append("  Closing: ").Append(Closing).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProblemCloseResult);
        }

        /// <summary>
        /// Returns true if ProblemCloseResult instances are equal
        /// </summary>
        /// <param name="input">Instance of ProblemCloseResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProblemCloseResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CloseTimestamp == input.CloseTimestamp ||
                    (this.CloseTimestamp != null &&
                    this.CloseTimestamp.Equals(input.CloseTimestamp))
                ) && 
                (
                    this.ProblemId == input.ProblemId ||
                    (this.ProblemId != null &&
                    this.ProblemId.Equals(input.ProblemId))
                ) && 
                (
                    this.Closing == input.Closing ||
                    (this.Closing != null &&
                    this.Closing.Equals(input.Closing))
                ) && 
                (
                    this.Comment == input.Comment ||
                    (this.Comment != null &&
                    this.Comment.Equals(input.Comment))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CloseTimestamp != null)
                    hashCode = hashCode * 59 + this.CloseTimestamp.GetHashCode();
                if (this.ProblemId != null)
                    hashCode = hashCode * 59 + this.ProblemId.GetHashCode();
                if (this.Closing != null)
                    hashCode = hashCode * 59 + this.Closing.GetHashCode();
                if (this.Comment != null)
                    hashCode = hashCode * 59 + this.Comment.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
